# Generated by Django 3.1.6 on 2021-05-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jackpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lucky_id', models.CharField(max_length=3)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
