# Generated by Django 3.1 on 2021-05-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=50)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
