# Generated by Django 3.1 on 2021-04-14 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210315_0237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
